version: '3.8'
services:
  app:
    image: ayumu277/chatbot-app:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
