/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'dark-bg': '#0D1117',
        'accent-blue': '#1E90FF',
        'gray-800': '#21262D',
        'gray-700': '#30363D',
        'gray-600': '#484F58',
        'gray-500': '#656D76',
        'gray-400': '#7D8590',
        'gray-300': '#9DAAB6',
        'gray-200': '#B1BAC4',
        'gray-100': '#C9D1D9',
        'gray-50': '#F0F6FC',
      },
      fontFamily: {
        'sans': ['Inter', 'Noto Sans JP', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      fontWeight: {
        'normal': '400',
        'medium': '500',
        'semibold': '600',
      },
    },
  },
  plugins: [],
  darkMode: 'class',

  // 🔥 本番環境でのCSS保持設定 - 全スタイルを強制的に保持
  mode: 'jit',
  purge: {
    enabled: false, // 本番環境でもpurgeを無効化
  },

  // 重要: 全てのTailwindクラスを保持
  safelist: [
    // 🎨 カラー系
    {
      pattern: /bg-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950)/,
    },
    {
      pattern: /text-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950)/,
    },
    {
      pattern: /border-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950)/,
    },
    // 🎨 カスタムカラー
    'bg-[#0D1117]',
    'bg-[#161B22]',
    'bg-[#21262D]',
    'bg-[#1E90FF]',
    'bg-dark-bg',
    'bg-accent-blue',
    'text-white',
    'text-gray-100',
    'text-gray-200',
    'text-gray-300',
    'text-gray-400',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-800',
    // 📐 レイアウト
    'flex',
    'flex-1',
    'flex-col',
    'flex-row',
    'grid',
    'block',
    'inline-block',
    'inline',
    'hidden',
    'h-screen',
    'h-full',
    'h-auto',
    'w-full',
    'w-64',
    'w-auto',
    'min-h-screen',
    'min-w-0',
    'max-w-4xl',
    'max-w-2xl',
    'max-w-xl',
    // 📏 スペーシング
    {
      pattern: /[mp][xytrbl]?-\d+/,
    },
    'space-y-4',
    'space-x-2',
    'gap-4',
    'gap-2',
    // 🔲 ボーダー・角丸
    'border',
    'border-2',
    'border-t',
    'border-b',
    'border-gray-600',
    'border-gray-700',
    'border-gray-800',
    'rounded',
    'rounded-lg',
    'rounded-md',
    'rounded-full',
    // 📍 ポジション
    'relative',
    'absolute',
    'fixed',
    'sticky',
    'inset-0',
    'inset-y-0',
    'top-0',
    'top-4',
    'left-0',
    'left-4',
    'right-0',
    'right-4',
    'bottom-0',
    'z-10',
    'z-20',
    'z-30',
    'z-40',
    'z-50',
    // 🎭 変形・アニメーション
    'transform',
    'transition-all',
    'transition-colors',
    'transition-transform',
    'duration-200',
    'duration-300',
    'ease-in-out',
    'translate-x-0',
    '-translate-x-full',
    'scale-105',
    'rotate-180',
    'animate-spin',
    'animate-pulse',
    'animate-bounce',
    // 🖱️ インタラクション
    'hover:bg-gray-700',
    'hover:bg-gray-800',
    'hover:bg-blue-600',
    'hover:bg-blue-700',
    'hover:text-white',
    'hover:scale-105',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-blue-500',
    'focus:ring-offset-2',
    'active:scale-95',
    // 📱 レスポンシブ
    'sm:block',
    'sm:hidden',
    'md:flex',
    'md:hidden',
    'md:block',
    'md:translate-x-0',
    'md:static',
    'lg:max-w-4xl',
    // 📄 テキスト
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'font-normal',
    'font-medium',
    'font-semibold',
    'font-bold',
    'text-center',
    'text-left',
    'text-right',
    'leading-relaxed',
    // 🌀 オーバーフロー
    'overflow-hidden',
    'overflow-y-auto',
    'overflow-x-hidden',
    'scrollbar-thin',
    'scrollbar-thumb-gray-600',
    'scrollbar-track-gray-800',
    // 🔧 その他
    'cursor-pointer',
    'pointer-events-none',
    'select-none',
    'whitespace-nowrap',
    'truncate',
    'break-words',
  ],
}
